function Notepad:_InitializeButtons()
	self:_InitializeToggleMinimizeButton()
	self:_InitializeAddNoteButton()
	self:_InitializeResizeButton()
end

function Notepad:_InitializeToggleMinimizeButton()
	self.Frame.ToggleMinimizeButton = CreateFrame("Button", nil, self.Frame, "BackdropTemplate")
	self.Frame.ToggleMinimizeButton:SetPoint("TOPRIGHT", self.Frame, -4, -2)
	self.Frame.ToggleMinimizeButton:SetText("-")
	self.Frame.ToggleMinimizeButton:SetSize(20, 20)
	self.Frame.ToggleMinimizeButton:SetNormalFontObject("GameFontNormalLarge")
	self.Frame.ToggleMinimizeButton:SetScript("OnClick", function ()
		self:ToggleMinimize()
	end)
end

function Notepad:_InitializeAddNoteButton()
	self.Frame.AddButton = CreateFrame("Button", nil, self.Frame, "GameMenuButtonTemplate")
	self.Frame.AddButton:SetPoint("TOPRIGHT", self.Frame, -10, -30)
	self.Frame.AddButton:SetSize(30, 21)
	self.Frame.AddButton:SetText("+")
	self.Frame.AddButton:SetNormalFontObject("GameFontNormalLarge")
	self.Frame.AddButton:SetScript("OnClick", function()
		self:AddNote(self.Frame.InputField:GetText(), true)
	end)
end

function Notepad:_InitializeResizeButton()
	self.Frame.ResizeButton = CreateFrame("Button", nil, self.Frame)
	self.Frame.ResizeButton:SetSize(12, 12)
	self.Frame.ResizeButton:SetPoint("BOTTOMRIGHT")
	self.Frame.ResizeButton:SetNormalTexture("Interface\\ChatFrame\\UI-ChatIM-SizeGrabber-Up")
	self.Frame.ResizeButton:SetHighlightTexture("Interface\\ChatFrame\\UI-ChatIM-SizeGrabber-Highlight")
	self.Frame.ResizeButton:SetPushedTexture("Interface\\ChatFrame\\UI-ChatIM-SizeGrabber-Down")

	self.Frame.ResizeButton:SetScript("OnMouseDown", function(_, button)
		self.Frame:StartSizing("BOTTOMRIGHT")
		self.Frame:SetUserPlaced(true)
	end)

	self.Frame.ResizeButton:SetScript("OnMouseUp", function(_, button)
		self.Frame:StopMovingOrSizing()
	end)

	self.Frame.LockButton = CreateFrame("Button", nil, self.Frame)
	self.Frame.LockButton:SetSize(22, 12)
	self.Frame.LockButton:SetText("lock")
	self.Frame.LockButton:SetPoint("BOTTOMLEFT", self.Frame, "BOTTOMRIGHT", -36, 4)
	self.Frame.LockButton:SetNormalFontObject("GameFontWhite")
	self.Frame.LockButton:SetAlpha(0.3)
	self.Frame.LockButton:SetScript("OnClick", function ()
		self:ToggleUILock(not self.isLocked)
	end)

	self.Frame.LockButton:SetScript("OnEnter", function()
		self.Frame.LockButton:SetAlpha(0.7)
		GameTooltip:SetOwner(self.Frame.LockButton, "ANCHOR_RIGHT")
		GameTooltip:SetText("Lock or unlock the window")
		GameTooltip:Show()
	end)

	self.Frame.LockButton:SetScript("OnLeave", function()
		self.Frame.LockButton:SetAlpha(0.3)
		GameTooltip:Hide()
	end)
end