function Notepad:_InitializeBorderGlow()
    self.Frame.HighlightBorder = self.Frame:CreateTexture("QN_HighlightBorder", "BORDER", nil)
    self.Frame.HighlightBorder:SetAllPoints()
    self.Frame.HighlightBorder:SetAtlas("communities-create-avatar-border-selected")
    self.Frame.HighlightBorder:SetAlpha(0)
    self.Frame.HighlightBorderAnimGroup = self.Frame.HighlightBorder:CreateAnimationGroup()
    local HighlightBorderFadeIn = self.Frame.HighlightBorderAnimGroup:CreateAnimation("Alpha")
    local HighlightBorderFadeOut = self.Frame.HighlightBorderAnimGroup:CreateAnimation("Alpha")
    HighlightBorderFadeIn:SetDuration(1)
    HighlightBorderFadeIn:SetFromAlpha(0)
    HighlightBorderFadeIn:SetToAlpha(1)
    HighlightBorderFadeIn:SetOrder(1)
    HighlightBorderFadeOut:SetDuration(1)
    HighlightBorderFadeOut:SetFromAlpha(1)
    HighlightBorderFadeOut:SetToAlpha(0)
    HighlightBorderFadeOut:SetOrder(2)
    self.Frame.HighlightBorderAnimGroup:SetLooping("REPEAT")

	self.Frame:SetScript("OnEnter", function ()
        self.Frame.HighlightBorderAnimGroup:Stop()
    end)
end